# Use the Maven image to build your application
FROM maven:3.8.5-openjdk-8 as build

# Set the working directory
WORKDIR /app

# Clone the Git repository into the working directory
RUN git clone https://github.com/teja384/Hiring-app-argocd.git .

# Build the application using Maven
RUN mvn clean package

# Use Tomcat as the base image for the runtime
FROM tomcat:8.5-jre8

# Set the working directory in Tomcat
WORKDIR /usr/local/tomcat/webapps/ROOT

# Copy the war file generated by Maven build into Tomcat's webapps folder
COPY --from=build /app/target/my-app.war /usr/local/tomcat/webapps/ROOT.war

# Expose the port Tomcat will run on
EXPOSE 8080

# Start Tomcat when the container runs
CMD ["catalina.sh", "run"]
